### PR TITLE
retrict updates of links to the one with empty link

### LINKED ISSUE #365: homepage: Learn about wrong link
The link "Learn about" on https://main--bitdefender--hlxsites.hlx.page/solutions/ is wrong. It should point to https://www.bitdefender.com.au/solutions/small-office-security.html

Screenshot 2023-09-26 at 17 45 02

### PR DESCRIPTION
**Pull request by nicolasbarbe**
Update button links only if their value is 'http://'

It allows to mix buttons with static links defined by the user in the word document and links (with http://) that will be automatically updated based on the chosen plan 

Fix #365

Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/
- After: https://fix-button-url--bitdefender--hlxsites.hlx.page/solutions/

### CODE REVIEW

File: blocks/products/products.js [hunk 1]
```diff
@@ -375,10 +375,11 @@ export default function decorate(block) {
 
       // listen to ProductCard change and update the first button accordingly
       mv.subscribe((card) => {
-        const link = col.querySelector('.button-container a');
-        if (link) {
-          link.href = card.url;
-        }
+        col.querySelectorAll('.button-container a').forEach((link) => {
+          if (link && link.href === 'http://') {
```
Comment (lansami) [inline blocks/products/products.js:379]: do we want to update the link only when is set to `http://`, I mean we don't want to do this when the link starts with `http://`?
I've checked the link for the PR and the line below is not reached on the `/solutions/` page

Comment (nicolasbarbe) [reply blocks/products/products.js:379]: > do we want to update the link only when is set to http://
Yes, Word forces the user to provide a value for the url, it cannot be blank. This is why I choose "http://"

Another alternative maybe is "https://www.bitdefender.com/site/Store/buy" which is the base url of the store.

> I've checked the link for the PR and the line below is not reached on the /solutions/ page
Thanks, will fix this.

Comment (nicolasbarbe) [reply blocks/products/products.js]: Fixed, if the link is equal to "https://www.bitdefender.com/site/Store/buy" it will be recalculated dynamiclaly to point to the right product in the store. Otherwise it will keep it as it is.

It has been fixed on:
- https://fix-button-url--bitdefender--hlxsites.hlx.page/solutions/ where the actual bug is fixed
- https://fix-button-url--bitdefender--hlxsites.hlx.page/solutions/total-security where the button is dynamically reclculated.

Comment (lansami) [reply blocks/products/products.js]: checked and it works fine

**Review by lansami — APPROVED** [review]
