### PR TITLE
Fix quote-carousel & carousel not rendering

### LINKED ISSUE #410: svgs not rendering inside quote-carousel block
related to: https://github.com/hlxsites/bitdefender/issues/395

where to reproduce: https://main--bitdefender--hlxsites.hlx.page/drafts/vlad/icons

### PR DESCRIPTION
**Pull request by andreibogdan**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #410 

Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/
- After: https://410-svgs-issue-quote-carrousel--bitdefender--hlxsites.hlx.page/solutions/

### CODE REVIEW

**Review by vradulescu-bd — APPROVED** [review]

**Comment by vradulescu-bd** [comment]
still reproducing on https://410-svgs-issue-quote-carrousel--bitdefender--hlxsites.hlx.page/drafts/vlad/icons

File: solutions/blocks/quote-carousel/quote-carousel.js [hunk 1]
```diff
@@ -8,14 +8,15 @@ function createSlide(item, index) {
   const paragraphs = Array.from(item.querySelectorAll('p'));
   const quote = paragraphs.find((paragraph) => {
     const strongOrEm = paragraph.querySelector('strong, em');
-    return !strongOrEm && paragraph.textContent.trim() !== '';
+    return !strongOrEm && paragraph.innerHTML !== '';
```
Comment (andreibogdan) [inline solutions/blocks/quote-carousel/quote-carousel.js:11]: try to remove it and see what is happening

**Review by vtsaplin — APPROVED** [review]
